apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  name: vg-rental-prometheus-rules-errorbudget
  namespace: vg-rental
  labels:
    app: vg-rental
    job: vg-rental
    release: prometheus
    team: sre
spec:
  groups:
  - name: SLOs-http_requests_total
    rules:
    - alert: Blockbuster-ErrorBudgetBurn
      annotations:
        message: 'High error budget burn for job=vg-rental (current value: {{ $value }})'
      expr: |
        sum(http_requests_total:burnrate5m{job="vg-rental"}) > (14.40 * (1-0.99900))
        and
        sum(http_requests_total:burnrate1h{job="vg-rental"}) > (14.40 * (1-0.99900))
      for: 2m
      labels:
        job: vg-rental
        severity: critical

    - alert: Blockbuster-ErrorBudgetBurn
      annotations:
        message: 'High error budget burn for job=vg-rental (current value: {{ $value }})'
      expr: |
        sum(http_requests_total:burnrate30m{job="vg-rental"}) > (6.00 * (1-0.99900))
        and
        sum(http_requests_total:burnrate6h{job="vg-rental"}) > (6.00 * (1-0.99900))
      for: 15m
      labels:
        job: vg-rental
        severity: critical

    - alert: Blockbuster-ErrorBudgetBurn
      annotations:
        message: 'High error budget burn for job=vg-rental (current value: {{ $value }})'
      expr: |
        sum(http_requests_total:burnrate2h{job="vg-rental"}) > (3.00 * (1-0.99900))
        and
        sum(http_requests_total:burnrate1d{job="vg-rental"}) > (3.00 * (1-0.99900))
      for: 1h
      labels:
        job: vg-rental
        severity: warning

    - alert: Blockbuster-ErrorBudgetBurn
      annotations:
        message: 'High error budget burn for job=vg-rental (current value: {{ $value }})'
      expr: |
        sum(http_requests_total:burnrate6h{job="vg-rental"}) > (1.00 * (1-0.99900))
        and
        sum(http_requests_total:burnrate3d{job="vg-rental"}) > (1.00 * (1-0.99900))
      for: 3h
      labels:
        job: vg-rental
        severity: warning

    - expr: |
        sum(rate(http_requests_total{job="vg-rental",code=~"5.."}[1d]))
        /
        sum(rate(http_requests_total{job="vg-rental"}[1d]))
      labels:
        job: vg-rental
      record: http_requests_total:burnrate1d

    - expr: |
        sum(rate(http_requests_total{job="vg-rental",code=~"5.."}[1h]))
        /
        sum(rate(http_requests_total{job="vg-rental"}[1h]))
      labels:
        job: vg-rental
      record: http_requests_total:burnrate1h

    - expr: |
        sum(rate(http_requests_total{job="vg-rental",code=~"5.."}[2h]))
        /
        sum(rate(http_requests_total{job="vg-rental"}[2h]))
      labels:
        job: vg-rental
      record: http_requests_total:burnrate2h

    - expr: |
        sum(rate(http_requests_total{job="vg-rental",code=~"5.."}[30m]))
        /
        sum(rate(http_requests_total{job="vg-rental"}[30m]))
      labels:
        job: vg-rental
      record: http_requests_total:burnrate30m

    - expr: |
        sum(rate(http_requests_total{job="vg-rental",code=~"5.."}[3d]))
        /
        sum(rate(http_requests_total{job="vg-rental"}[3d]))
      labels:
        job: vg-rental
      record: http_requests_total:burnrate3d

    - expr: |
        sum(rate(http_requests_total{job="vg-rental",code=~"5.."}[5m]))
        /
        sum(rate(http_requests_total{job="vg-rental"}[5m]))
      labels:
        job: vg-rental
      record: http_requests_total:burnrate5m
      
    - expr: |
        sum(rate(http_requests_total{job="vg-rental",code=~"5.."}[6h]))
        /
        sum(rate(http_requests_total{job="vg-rental"}[6h]))
      labels:
        job: vg-rental
      record: http_requests_total:burnrate6h