apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  name: vg-rental-prometheus-rules-database
  namespace: blockbuster
  labels:
    app: vg-rental
    job: vg-rental
    release: prometheus
    team: sre
spec:
  groups:
  - name: Blockbuster-Emails-Sent
    rules:
    - alert: DatabaseErrorLimit
      annotations:
        message: 'Database errors are beyond capacity'
      expr: |
        (sum(rate(connection_attempt_total{type="success",}[2m])) / sum(rate(connection_attempt_total[2m]))) < 99.9
      for: 2m
      labels:
        namespace: blockbuster
        severity: critical
    - alert: DatabaseErrorLimit
      annotations:
        message: 'Database errors are beyond capacity'
      expr: |
        (sum(rate(connection_attempt_total{type="success",}[15m])) / sum(rate(connection_attempt_total[15m]))) < 99.9
      for: 15m
      labels:
        namespace: blockbuster
        severity: critical
    - alert: DatabaseErrorLimit
      annotations:
        message: 'Database errors are approaching capacity capacity'
      expr: |
        (sum(rate(connection_attempt_total{type="success",}[2m])) / sum(rate(connection_attempt_total[2m]))) < 99.95
      for: 2m
      labels:
        namespace: blockbuster
        severity: warning
    - alert: DatabaseErrorLimit
      annotations:
        message: 'Database errors are approaching capacity capacity'
      expr: |
        (sum(rate(connection_attempt_total{type="success",}[2m])) / sum(rate(connection_attempt_total[2m]))) < 99.95
      for: 15m
      labels:
        namespace: blockbuster
        severity: warning