apiVersion: monitoring.coreos.com/v1
kind: Prometheus
metadata:
    name: prometheus
    namespace: blockbuster
spec:
  serviceAccountName: prometheus
  serviceMonitorSelector:
    matchLabels:
      env: production
  resources:
    requests:
      memory: 400Mi