apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: blockbuster-prometheus
  namespace: blockbuster
  labels:
    env: production
spec:
  endpoints:
  - interval: 30s
    port: web
  selector:
    matchLabels:
      app: prometheus